language: go

go:
- 1.12.x

env:
- GO111MODULE=on

services:
- mongodb

before-install:
- go run assets/asset_generate.go

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
- go vet ./...
